version: '3.8'

services:
  mulm:
    build: .
    container_name: mulm_app
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    volumes:
      - /var/basny:/mnt/data
    networks:
      - web

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/default.conf.template
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    networks:
      - web
    depends_on:
      - mulm
    environment:
      - DOMAIN=${DOMAIN}

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    # For automatic renewal (uncomment after initial setup)
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

networks:
  web:
    driver: bridge
