services:
  nginx-local-proxy:
    image: nginx:alpine
    container_name: basny-nginx-local-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.local-proxy.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    restart: unless-stopped
    networks:
      - default
    # Resource limits
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 64M
    # Security hardening
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - SETUID
      - SETGID

networks:
  default:
    name: basny-local-proxy
