name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide details about what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the use case?
      placeholder: I'm frustrated when... / It would be helpful if...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: Describe your ideal solution
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Feature Area
      description: Which part of the application would this affect?
      options:
        - Submission Form
        - Admin Tools
        - Species Database
        - User Account
        - Awards/Points
        - Activity Feed
        - Reporting/Analytics
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this to you?
      options:
        - Critical (blocking important work)
        - High (would significantly improve workflow)
        - Medium (nice to have)
        - Low (minor convenience)

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other solutions have you considered or tried?

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Screenshots, mockups, examples from other systems, etc.
